#!/usr/bin/env python3
"""
Hist_Error_Comparison_AllModes.py
---------------------------------------------------
Visualizes and compares absolute prediction error distributions
for XGBoost models trained on multiple preprocessing modes (mode1–mode4),
each with three target definitions:
    1. Direct Energy Prediction
    2. Scaled Ratio
    3. Log-Scaled Ratio

Functionality:
--------------
- Loads comparison CSVs generated by Compare_XGB_AllModes.py:
      model/model_<mode>_comparisons/comparison_<mode>.csv
- Extracts absolute errors for all three targets.
- Applies a cutoff to remove extreme outliers.
- Plots a 2×2 grid of subplots, one per mode.
- Each subplot overlays |Error_direct_energy|, |Error_scaled_ratio|,
  and |Error_log_scaled_ratio| histograms for side-by-side comparison.
- Uses identical y-limits across all plots for fair visual comparison.

Output:
-------
- A single PNG figure: `hist_error_all_modes.png` saved in the figures directory.
"""

import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ================================================================
# Configuration
# ================================================================
with open("config.json", "r") as f:
    config = json.load(f)

MODEL_DIR = config.get("models_dir", "model")
FIGURES_DIR = config.get("figures_dir", "figures")
os.makedirs(FIGURES_DIR, exist_ok=True)

MODES = ["mode1", "mode2", "mode3", "mode4"]
TARGETS = ["direct_energy", "scaled_ratio", "log_scaled_ratio"]
ERROR_CUTOFF = 1e20
BINS = 40
SAVE_FIG = True
OUT_FIG_PATH = os.path.join(FIGURES_DIR, "hist_error_all_modes.png")

# Color scheme for clarity
COLOR_MAP = {
    "direct_energy": "blue",
    "scaled_ratio": "red",
    "log_scaled_ratio": "green"
}
LABELS = {
    "direct_energy": "Direct Energy",
    "scaled_ratio": "Ratio-Based",
    "log_scaled_ratio": "Log-Ratio-Based"
}

# ================================================================
# Load and prepare error data
# ================================================================
error_data = {}

for mode in MODES:
    csv_path = os.path.join(MODEL_DIR, f"model_{mode}_comparisons", f"comparison_{mode}.csv")
    if not os.path.exists(csv_path):
        print(f"[WARNING] Missing comparison file for {mode}: {csv_path}")
        continue

    df = pd.read_csv(csv_path)
    mode_errors = {}
    for tgt in TARGETS:
        col = f"|Error_{tgt}|"
        if col in df.columns:
            errs = df[col].values
            errs = errs[np.isfinite(errs)]
            errs = errs[errs < ERROR_CUTOFF]
            mode_errors[tgt] = errs
    error_data[mode] = mode_errors

# ================================================================
# Determine global y-limit for visual consistency
# ================================================================
ymax = 0
for mode, errs in error_data.items():
    for tgt in TARGETS:
        if tgt in errs:
            counts, _ = np.histogram(errs[tgt], bins=BINS)
            ymax = max(ymax, counts.max())

# ================================================================
# Plot 2×2 grid of histograms
# ================================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, mode in enumerate(MODES):
    ax = axes[idx]
    if mode not in error_data:
        ax.text(0.5, 0.5, f"No data for {mode}", ha="center", va="center", fontsize=12, color="gray")
        ax.axis("off")
        continue

    for tgt in TARGETS:
        if tgt not in error_data[mode]:
            continue
        errs = error_data[mode][tgt]
        ax.hist(
            errs,
            bins=BINS,
            alpha=0.5,
            color=COLOR_MAP[tgt],
            label=LABELS[tgt],
        )

    ax.set_yscale("log")
    ax.set_ylim(1, ymax * 1.2)
    ax.set_xlabel("|Error| = |E_pred - E_true|")
    ax.set_ylabel("Frequency (log scale)")
    ax.set_title(f"Absolute Error Distribution — {mode}")
    ax.grid(True, which="both", linestyle="--", alpha=0.6)
    ax.legend(fontsize=9)

# Hide unused axes if fewer than 4 modes exist
for j in range(len(MODES), len(axes)):
    axes[j].axis("off")

plt.tight_layout()
plt.suptitle("Absolute Error Distributions across Modes and Targets", fontsize=14, y=1.02)
plt.subplots_adjust(top=0.92)

# ================================================================
# Save or Show
# ================================================================
if SAVE_FIG:
    plt.savefig(OUT_FIG_PATH, dpi=200, bbox_inches="tight")
    print(f"[INFO] Saved histogram figure to: {OUT_FIG_PATH}")

plt.show()
